### ISSUE TITLE
Popup container gets in the way

### ISSUE THREAD

**Issue by ukupat** [react-component/trigger#48]
We **upgraded from version 1.8.2 to 1.8.3** and found out that it isn't possible to interact with elements that are close to rc-trigger component anymore. I hope this screenshot explains more:

![screen shot 2017-04-04 at 14 06 46](https://cloud.githubusercontent.com/assets/4997766/24653846/2c8eec5c-1940-11e7-86b4-0ded8e55b83b.png)

It seems that https://github.com/react-component/trigger/commit/2e4adf7db83a9e4fe30b14d57715881f77ef226e has caused this problem.

**Comment by njpatel** [comment]
This also effects clicking outside to close the popover, the popover container remains in the way and stops other input from reaching the rest of the web app. Confirmed that reverting the above commit fixes the issue.

**Comment by benjycui** [comment]
An online demo will be better, thanks.

**Comment by jseminck** [comment]
Hello, I have created a test repository that shows this issue. See the screenshot below.

Test-app is made with `create-react-app`. Just run `yarn start` and it will run itself. As you can see, clicking on any of the buttons is not possible because of a hidden overlay created by rc-trigger. 

If you remove the popup (by setting the initial visible state to `false` then the buttons interaction works, until the actual popup becomes visible).

Repo: https://github.com/jseminck/rc-trigger-issue

In this case, reverting the changes that were pointed out in the original comment also work. But I do not yet understand what implications that revert has for any of the other cases.

If you need any more information from me, please let me know. 

<img width="1304" alt="screen shot 2017-06-02 at 08 14 51" src="https://cloud.githubusercontent.com/assets/9586897/26711843/e99b23e8-476b-11e7-8400-2dd129d6ef85.png">

**Comment by benjycui** [comment]
Just import rc-trigger's style in your code:

```jsx
import 'rc-trigger/assets/index.css';
```

**Comment by jseminck** [comment]
While that may work, it doesn't seem like an elegant solution. This import is also not documented, so if you would change the internal folder structure then it would break.

Are you sure the change in https://github.com/react-component/trigger/commit/2e4adf7db83a9e4fe30b14d57715881f77ef226e#diff-afbf9d41312aa7a036d65ed5e35fc955R69 is really needed?

**Comment by benjycui** [comment]
Actually, the problem is: if we don't set `position: absolute`, dom-align will set it to [`position: relative`](https://github.com/yiminghe/dom-align/blob/301a12d95211e8556c4fd9a008ace614321dda6b/src/utils.js#L217) automatically.

So we need to import the default style.

Or can we just [set popup element to `position: absolute` in JS](https://github.com/react-component/trigger/blob/d6789a165c8e7517a0a2a080be615210f32f2303/src/Popup.jsx#L79-L82). @yiminghe

**Comment by benjycui** [comment]
ping @afc163 @yiminghe

**Comment by afc163** [comment]
👌

**Comment by benjycui** [comment]
@MrPeak 试下？
